import { Router } from "express";
import { adminAuthRouter } from "../modules/auth/auth.routes.js";
import { staffAdminRouter } from "../modules/staff/staff.routes.js";
import { roleAdminRouter } from "../modules/roles/role.routes.js";
import { permissionAdminRouter } from "../modules/permissions/permission.routes.js";
import { rbacAdminRouter } from "../modules/rbac/rbac.routes.js";
import { shopkeeperAdminRouter } from "../modules/shopkeepers/shopkeeper.routes.js";
import { mediaAdminRouter } from "../modules/media/media.routes.js";
import { metalAdminRouter } from "../modules/metals/metal.routes.js";
import { categoryAdminRouter } from "../modules/categories/category.routes.js";
import { productAdminRouter } from "../modules/products/product.routes.js";
import { productVariantAdminRouter } from "../modules/product-variants/product-variant.routes.js";
import { pricingAdminRouter } from "../modules/pricing/pricing.routes.js";
import { inventoryAdminRouter } from "../modules/inventory/inventory.routes.js";
import { orderAdminRouter } from "../modules/orders/order.routes.js";
import { paymentAdminRouter } from "../modules/payments/payment.routes.js";
import { deliveryAdminRouter } from "../modules/delivery/delivery.routes.js";
import { reportAdminRouter } from "../modules/reports/report.routes.js";
import { auditLogAdminRouter } from "../modules/audit-logs/audit-log.routes.js";
import { accountsLedgerAdminRouter } from "../modules/accounts-ledger/accounts-ledger.routes.js";
import { metalLedgerShopAdminRouter } from "../modules/metal-ledger/ledger.routes.js";
import { metalLedgerTransactionAdminRouter } from "../modules/metal-ledger/ledger.routes.js";
import { khatabookAdminRouter } from "../modules/khatabook/khatabook.routes.js";

const router = Router();

router.use("/auth", adminAuthRouter);
router.use("/staff", staffAdminRouter);
router.use("/roles", roleAdminRouter);
router.use("/permissions", permissionAdminRouter);
router.use("/rbac", rbacAdminRouter);
router.use("/shopkeepers", shopkeeperAdminRouter);
router.use("/media", mediaAdminRouter);
router.use("/metals", metalAdminRouter);
router.use("/categories", categoryAdminRouter);
router.use("/products", productAdminRouter);
router.use("/product-variants", productVariantAdminRouter);
router.use("/pricing", pricingAdminRouter);
router.use("/inventory", inventoryAdminRouter);
router.use("/orders", orderAdminRouter);
router.use("/payments", paymentAdminRouter);
router.use("/delivery", deliveryAdminRouter);
router.use("/reports", reportAdminRouter);
router.use("/audit-logs", auditLogAdminRouter);
router.use("/accounts-ledger", accountsLedgerAdminRouter);
router.use("/shops", metalLedgerShopAdminRouter);
router.use("/ledger-transactions", metalLedgerTransactionAdminRouter);
router.use("/khatabook", khatabookAdminRouter);

export default router;
